name: Fail if InterSystems npm package is outdated
on:
  schedule:
  - cron: '45 12 * * 4' # Runs every Thursday at 12:45 UTC

jobs:
  check-if-outdated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Show npm version
        run: npm --version

      - name: Install dependencies
        run: npm install

      - name: Check for outdated ISC package
        run: npm outdated @intersystems/intersystems-iris-native
